[CMS-23418] documentation (main)
CoreMedia/content-hub-adapter-rss pull request #22
Opened 2024-12-02 14:56 UTC by rwaterma

autoclose none

2025-01-27 16:10 UTC, stefanpieper commented on documentation/installation.md
> +   Add the absolute path of the `content-hub-adapter-rss/studio-client/apps/main/content-hub-adapter-rss` directory
Won't that cause a clash as the default Blueprint Studio Client build will already download the default RSS plugin? See `apps/studio-client/apps/main/app/plugins.json`.

2025-01-27 16:10 UTC, stefanpieper commented on documentation/installation.md
> +   Add the absolute path of the `content-hub-adapter-rss/studio-client/apps/main/content-hub-adapter-rss` directory
And is it really the given path - without the `build` directory?

2025-01-28 12:15 UTC, stefanpieper commented on documentation/installation.md
> +   Add the absolute path of the `content-hub-adapter-rss/studio-client/apps/main/content-hub-adapter-rss` directory
A note like you propose (_"If the plugin is already bundled in your Blueprint version..."_) would surely help. In case people want to adjust the plugin and replace the bundled one, they could be made aware of the `plugins.json` to check for and remove an already bundled version.

2025-01-28 15:23 UTC, stefanpieper requested changes

2025-01-28 15:38 UTC, rwaterma commented on documentation/installation.md
> +* If the plugin is already bundled in your Blueprint version (check the `plugins.json` file of the `studio-server` app), you can immediately proceed with [Configure the Plugin](#configure-the-plugin)
Removing bundled plugins is hopefully documented in the Blueprint documentation.  I would not like to go into such details here.  If the process ever changes, e.g. another step to do, it would be surely be forgotten to change it here.

2025-01-28 16:43 UTC, stefanpieper approved these changes

2025-02-05 10:27 UTC, merged